feature/ADM-681 add forecast OAS3 spec
3AP-AG/harvest-forecast-client pull request #4
Opened 2020-11-10 10:16 UTC by jamescallumyoung

This PR adds an implementation for the Harvest Forecast API specification in OpenAPI3 format. The Spec is split into component parts for readability and maintainability, and is found in the `src/spec` directory. `src/spec/index.yaml` is the entry point.

This PR also adds additionally tooling that can be used to work with the spec, most notably linting and resolving.

The resolve operation merges the numerous files into a single file - resolving the `$ref`s - and outputs that file for use elsewhere. This is necessary as most OAS3 tools expect a single file.

This PR *does not* handle the Java client generation. The work is split into two PRs for the sake of readability.

**TESTING**

First, visually inspect the numerous `.yaml` files in the `src/spec` directory; these make up the specification.

Next, you can lint the files with `yarn lint` and inspect the resolved output with `yarn serve`.

If you want to resolve the spec into a file you can inspect manually, or upload to a OAS3 editor (such as https://editor.swagger.io/), you can use `yarn resolve` and copy the output file. 

*N.B. You may need to `chmod +x` the scripts in the `scripts` dir before using the `yarn` commands mentioned above.

2020-11-10 10:25 UTC, jamescallumyoung commented
**Note:** The resolved output inlines the first use of a reference. Any future uses fo that reference are then replaced to a reference to the inlined version. This makes the resolved file ugly so I recommend inspecting with the `yarn serve` command.

2020-11-10 14:57 UTC, pschmechel approved these changes
The generated java dates are objects, the Inline classes look weird. I'm only going to use the AssignmentsApi - so most of the code is not needed. As a first step I guess it's OK. 
Is the next PR going to contain the maven project with generated java code? Then it could include the improvements.

2020-11-10 15:09 UTC, jamescallumyoung commented on .gitignore
> +# .idea/modules
Hah 😆 This is the intelliJ config from gitignore.io. It auto-generates for each repo I initialize. I actually added the whole `.idea` dir at the end anyway so I suppose this isn't needed anymore 👍

2020-11-11 06:54 UTC, gabac requested changes
I have troubles understanding why the introduction of JS was necessary. IMHO it just complicates this simple repo

2020-11-11 06:54 UTC, gabac commented on gen-conf.yaml
> +dateLibrary: java8
remove this as not needed

2020-11-11 06:54 UTC, gabac commented on openapitools.json
> +{
remove this as not needed

2020-11-11 06:54 UTC, gabac commented on package.json
> +    "@openapitools/openapi-generator-cli": "^2.1.3",
remove this as not needed. We want to generate the code through `mvn`. The goal with this repo is to provide a maven package

2020-11-11 06:54 UTC, gabac commented on src/main/resources/harvest-forecast-api.yaml
> -openapi: 3.0.1
Please add this back.

2020-11-11 06:54 UTC, gabac commented on src/spec/index.yaml
> +      bearerFormat: JWT
Did you try this? I only saw it working so far with a personal access token

2020-11-11 12:35 UTC, jamescallumyoung commented on .gitignore
> +# .idea/modules
I updated the ignore file 😆

2020-11-11 12:36 UTC, jamescallumyoung commented on openapitools.json
> +{
I removed this in the second PR (#5) but since that seemed to just confuse the PR process, I merged those changes into this PR. This file was removed.

2020-11-11 12:37 UTC, jamescallumyoung commented on gen-conf.yaml
> +dateLibrary: java8
I split this into two PRs and the second one handled using Maven to generate the code. This file was removed in that PR. It seems like having two PRs for this was causing some confusion so I closed that PR and applied its changes here too.

2020-11-11 12:38 UTC, jamescallumyoung commented on package.json
> +    "@openapitools/openapi-generator-cli": "^2.1.3",
See my comment below.

2020-11-11 13:33 UTC, jamescallumyoung commented
> I have troubles understanding why the introduction of JS was necessary. IMHO it just complicates this simple repo

@gabac I agree it adds some complexity but we can't really avoid it unfortunately. To split the OAS3 spec into smaller files we have to a method to Resolve them into a single  file for the generator plugin to consume. Speccy is the leading tool for this and it's only provided via NPM.

However, I did simplify the process somewhat. In the workflows, Yarn is now only used to install speccy; the resolving is executed directly by the included resolve.sh script (it uses speccy internally).

I've also added explicit instructions and an explenation to the README to clarify what role Yarn plays in the build process.

2020-11-11 13:42 UTC, jamescallumyoung commented on src/spec/index.yaml
> +      bearerFormat: JWT
This is the way we're currently calling the API from Paw. We use a Bearer token.

Using the OAuth security type in OAS3 would generate OAuth auth logic in the generated client. SInce we provide an accesstoken to the service already (see the env params needed for harvest-client), we don't need that. We can just use that token.

2020-11-11 13:45 UTC, gabac commented
To split the file into multiple has been a personal preference by you. IMHO this is not needed (you find a lot of big spec files if you look around in the internet. Best example is e..g the Sprint pet store) but we can go ahead...

Please have a look at these points

- [ ] GH Action Build error
- [ ] Commit the final file. 
- [ ] Security spec as mentioned already

2020-11-11 13:46 UTC, jamescallumyoung commented on src/main/resources/harvest-forecast-api.yaml
> -openapi: 3.0.1
The API spec is still here but has been split into smaller files. This is recommended by OpenAPI when writing long APIs. WIthout splitting, the file is huge and can be hard to read.

Resolving the `$ref`s into a single file is what Specy is needed for.

2020-11-11 13:46 UTC, jamescallumyoung commented on src/main/resources/harvest-forecast-api.yaml
> -openapi: 3.0.1
There is currently an incompatibility between Speccy and Openapi-generator which I'm working on.

2020-11-11 14:05 UTC, gabac commented on src/spec/index.yaml
> +      bearerFormat: JWT
Again did you try this? E.g. through swagger-editor.io?

My config has been and this did work

2020-11-11 14:07 UTC, gabac commented on src/main/resources/harvest-forecast-api.yaml
> -openapi: 3.0.1
>  This is recommended by OpenAPI
Can you link me the recommendation. Need to learn new stuff :D 

> There is currently an incompatibility between Speccy and Openapi-generator which I'm working on.
Doesn't speccy just stitches the files together?

2020-11-11 14:12 UTC, jamescallumyoung commented on src/main/resources/harvest-forecast-api.yaml
> -openapi: 3.0.1
> Can you link me the recommendation. Need to learn new stuff :D
Yeah, I'll dig out some good recommendations for OpenAPI stuff later. There's a really good talk by Twilio on how they use it.

> Doesn't speccy just stitches the files together?
It injects the referenced item into the root file in the first place it's referenced, then rewrites all the subsequent references to point to that one. Seems like the way it rewrites the references breaks openapi-generator. Looking at the two tools, I think it's an issue in openapi-generator not being fully spec compliant.

I'm going to resolve the file and manually fix it for now and we can look at splitting the spec up at a later point if someone else supports the idea too.

2020-11-11 14:15 UTC, jamescallumyoung commented on src/spec/index.yaml
> +      bearerFormat: JWT
This...

```
securitySchemes:
    forecast_auth:
      type: http
      scheme: bearer
```

...is actually the same. The `bearerFormat` is actually just a hint to the client and doesn't effect the functionality.

And the second part...

```
forecast_account_id:
      type: apiKey
      name: forecast-account-id
      in: header
```

... I included in each request using a $ref.

2020-11-11 14:16 UTC, jamescallumyoung commented on src/spec/index.yaml
> +      bearerFormat: JWT
> Again did you try this? E.g. through swagger-editor.io?

Yup 👍

2020-11-11 14:22 UTC, gabac commented on src/spec/index.yaml
> +      bearerFormat: JWT
Interesting because it doesn't work for me
![image](https://user-images.githubusercontent.com/50061/98822909-b0044780-2431-11eb-9bb1-9bbfcb8cecbb.png)

2020-11-11 14:22 UTC, gabac commented on src/spec/index.yaml
> +      bearerFormat: JWT
Also I think `forecast_account_id:` is nicer than adding it to every endpoint. Makes configuring the webclient easier

2020-11-11 14:46 UTC, jamescallumyoung commented on src/main/resources/harvest-forecast-api.yaml
> -openapi: 3.0.1
I added this file back and removed the split files due to the incompatibility between speccy and openapi-generator.  The resulting spec file is ~1000 lines but as you mentioned, there are quite a few long specs online so I guess we can live with it.

2020-11-11 14:52 UTC, jamescallumyoung commented on src/spec/index.yaml
> +      bearerFormat: JWT
> Also I think adding forecast_account_id to the securitySchemes is nicer than adding it to every endpoint.
You only have to set this once in the webClient

Yep! I think your solution is much cleaner. I'll make that change now.

2020-11-11 15:13 UTC, jamescallumyoung commented
Given the incompatibility between Speccys "resolved" single-file output and openapi-generator, I have updated this PR to provide the API spec as a single file.

Whilst I think splitting the spec into smaller files does provide some advantages, @gabac quite rightly pointed out that it does add some complecity and there are many popular large single-file API specs online.

2020-11-11 15:40 UTC, gabac commented on src/main/resources/harvest-forecast-api.yaml
> +        - whoami
you need to add this back to every endpoint
```
security: 
      - forecast_auth: []
      - forecast_account_id: []
```

2020-11-11 16:06 UTC, jamescallumyoung commented on src/main/resources/harvest-forecast-api.yaml
> +        - whoami
@gabac I had missed adding the `forecast_account_id` global security schema. I updated it so if you now check lines 18-20, you'll see both securitySchemes are applied globally.

2020-11-12 06:15 UTC, gabac commented on src/main/resources/harvest-forecast-api.yaml
> +        - whoami
Ah nice one! Good to know that this can be applied globally 👍

2020-11-12 06:15 UTC, gabac approved these changes

2020-11-12 06:16 UTC, gabac commented
@pschmechel Can you verify that now the generated code is as expected? 
Other than that we can merge this 👍

2020-11-12 07:47 UTC, pschmechel commented on .github/workflows/maven.yml
>          java-version: 14
Shouldn't we defult to 11? Same thing in pom.xml

2020-11-12 08:30 UTC, pschmechel commented
Checked with jdk 11 - the generated classes are now OK. If we should use jdk 11 the pom needs an update. Other than that the PR can be merged.

2020-11-12 10:13 UTC, jamescallumyoung commented on .github/workflows/maven.yml
>          java-version: 14
See below.

2020-11-12 10:16 UTC, jamescallumyoung commented
After discussing this with the Admin team in the Daily, we agreed to set the Java version to 11 as the services that will use this client run on 11. (Java 11 is the latest LTS release.)

I guess selecting Java 14 was not intentional (or, at least not needed) @gabac ?

I'll update the PR now. Please **do not merge the PR** as I want to do rebase it to clean up the commit history.

2020-11-12 11:00 UTC, gabac commented
> I guess selecting Java 14 was not intentional (or, at least not needed) @gabac ?

It was intentional but just to play around with things. You can use Java 11

2020-11-12 11:40 UTC, pschmechel approved these changes
Looks ok!

2020-11-12 11:49 UTC, gabac approved these changes

2020-11-12 12:50 UTC, jamescallumyoung commented
I will merge once the tests pass. I rebased the commits into two: one for the implementation, and another for updating the java version.

2020-11-12 12:57 UTC, merged